AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  graphql-service

  Sample SAM Template for graphql-service

Parameters:
  Stage:
    Type: String
    Default: DEV

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 1
    MemorySize: 3008
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  # This is a custom build layer. See:
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html
  CopyDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./apollo
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: makefile              # Required to have AWS SAM build this layer

  GenerateCertificate: # Creates a valid certificate for the HTTP API endpoint under the custom domain 
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: "api.graphql.fastchargeapi.com"
      ValidationMethod: DNS
      DomainValidationOptions:
      - DomainName: "api.graphql.fastchargeapi.com"
        HostedZoneId: Z0358815GI2I8U5CTHXW
        
  GenerateIAMCertificate: # Creates a valid certificate for the HTTP API endpoint under the custom domain 
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: "api.iam.graphql.fastchargeapi.com"
      ValidationMethod: DNS
      DomainValidationOptions:
      - DomainName: "api.iam.graphql.fastchargeapi.com"
        HostedZoneId: Z0358815GI2I8U5CTHXW

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        DomainName: "api.graphql.fastchargeapi.com"
        CertificateArn: !Ref GenerateCertificate
        Route53:
          HostedZoneId: Z0358815GI2I8U5CTHXW
      StageName: !Ref Stage
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: True
          ResourcePath: "/*" # allows for logging on any resource
          HttpMethod: "*" # allows for logging on any method
      Auth: # Uses the FirebaseTokenAuthorizer to identify the session user. 
        ApiKeyRequired: false
        DefaultAuthorizer: FirebaseTokenAuthorizer
        Authorizers:
          FirebaseTokenAuthorizer:
            FunctionArn: arn:aws:lambda:us-east-1:887279901853:function:auth-service-FirebaseTokenAuthorizer-P6dNbG2HV6tE
      Cors:
        AllowMethods: "'*'"
        AllowOrigin: "'*'"
        
  # Create another gateway with IAM based authentication
  APIGatewayIAM:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        DomainName: "api.iam.graphql.fastchargeapi.com"
        CertificateArn: !Ref GenerateIAMCertificate
        Route53:
          HostedZoneId: Z0358815GI2I8U5CTHXW
      StageName: !Ref Stage
      MethodSettings:
        - LoggingLevel: INFO
          MetricsEnabled: True
          ResourcePath: "/*" # allows for logging on any resource
          HttpMethod: "*" # allows for logging on any method
      Auth: # Uses the FirebaseTokenAuthorizer to identify the session user. 
        DefaultAuthorizer: AWS_IAM

  ApolloServer:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./apollo
      Handler: lambdaHandler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Policies:
        - AmazonDynamoDBFullAccess # Give the Lambda service access to poll your DynamoDB Stream
      Events:
        Get:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref APIGateway
        Post:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref APIGateway
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - lambdaHandler.ts

  ApolloServerIAM:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./apollo
      Handler: lambdaHandler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Policies:
        - AmazonDynamoDBFullAccess # Give the Lambda service access to poll your DynamoDB Stream
      Environment:
        Variables:
          TRUST_X_USER_EMAIL_HEADER: "0" # WARNING: X-User-Email must not be trusted in production.
      Events:
        PostIAM:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref APIGatewayIAM
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - lambdaHandler.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  APIGateway:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
  ApolloServer:
    Description: "ApolloServer ARN"
    Value: !GetAtt ApolloServer.Arn
  ApolloServerIamRole:
    Description: "Implicit IAM Role created (ApolloServerRole)"
    Value: !GetAtt ApolloServerRole.Arn
