version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    volumes:
      - ".docker/dynamodb/local:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-test:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-test
    ports:
      - "9001:8000"
    volumes:
      - ".docker/dynamodb/test:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
