AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: echo-service

Parameters:
  MainDomain:
    Type: String
  Route53ZoneId:
    Type: String
  EnvDevDomain:
    Type: String
    Default: ""
  SubDomain:
    Type: String
    Default: "api.echo."

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 1
    MemorySize: 128
    Environment:
      Variables:
        DEV_DOMAIN: !Ref EnvDevDomain

Resources:
  GenerateCertificate: # Creates a valid certificate for the HTTP API endpoint under the custom domain
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join ["", [!Ref SubDomain, !Ref MainDomain]]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Join ["", [!Ref SubDomain, !Ref MainDomain]]
          HostedZoneId: !Ref Route53ZoneId

  APIGatewayV2:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub ${AWS::StackName}-APIGatewayV2
      Domain: # Configure the domain of the API
        DomainName: !Join ["", [!Ref SubDomain, !Ref MainDomain]]
        CertificateArn: !Ref GenerateCertificate
        Route53:
          HostedZoneId: !Ref Route53ZoneId
      DisableExecuteApiEndpoint: True

  EchoGo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: !Sub ${AWS::StackName}-EchoGo
      CodeUri: ./go
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        AnyRoot:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref APIGatewayV2
        Any:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref APIGatewayV2
