version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-auth-service"
s3_prefix = "dev-auth-service"
region = "us-east-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MainDomain=\"devfastchargeapi.com\" Route53ZoneId=\"Z07362872NENGXHWMNLU5\" EnvDevDomain=\"1\""
image_repositories = []
no_fail_on_empty_changeset = true

[default.logs.parameters]
stack_name = "dev-auth-service"

[live]
[live.deploy]
[live.deploy.parameters]
profile = "live_fastchargeapi"
stack_name = "live-auth-service"
s3_prefix = "live-auth-service"
region = "us-east-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MainDomain=\"fastchargeapi.com\" Route53ZoneId=\"Z0358815GI2I8U5CTHXW\""
image_repositories = []
no_fail_on_empty_changeset = true

[live.logs.parameters]
profile = "live_fastchargeapi"
stack_name = "live-auth-service"
