AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth-service

  Sample SAM Template for auth-service

Parameters:
  Stage:
    Type: String
    Default: DEV

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  FirebaseTokenAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: authorizer.lambda_handler
      Runtime: python3.9
      Architectures:
        # - x86_64
        - arm64 # if you are using Apple M1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # ProxyApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/echo"
  FirebaseTokenAuthorizer:
    Description: FirebaseTokenAuthorizer ARN
    Value: !GetAtt FirebaseTokenAuthorizer.Arn
  FirebaseTokenAuthorizerIamRole:
    Description: Implicit IAM Role created for FirebaseTokenAuthorizer
    Value: !GetAtt FirebaseTokenAuthorizerRole.Arn
