version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-payment-service"
s3_prefix = "dev-payment-service"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ServicePrefix=\"dev\" MainDomain=\"devfastchargeapi.com\" Route53ZoneId=\"Z07362872NENGXHWMNLU5\" EnvDevDomain=\"1\""
image_repositories = []
no_fail_on_empty_changeset =  true

[default.logs.parameters]
stack_name = "dev-payment-service"

[live]
[live.deploy]
[live.deploy.parameters]
profile="live_fastchargeapi"
stack_name = "live-payment-service"
s3_prefix = "live-payment-service"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ServicePrefix=\"live\" MainDomain=\"fastchargeapi.com\" Route53ZoneId=\"Z0358815GI2I8U5CTHXW\""
image_repositories = []
no_fail_on_empty_changeset =  true

[live.logs.parameters]
profile = "live_fastchargeapi"
stack_name = "live-payment-service"
