AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  resource-service

  Sample SAM Template for resource-service

Parameters:
  Stage:
    Type: String
    Default: DEV
  HostName: 
    Type: String
    Default: "api.payment.fastchargeapi.com"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  GenerateCertificate: # Creates a valid certificate for the HTTP API endpoint under the custom domain 
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref HostName
      ValidationMethod: DNS
      DomainValidationOptions:
      - DomainName: !Ref HostName
        HostedZoneId: Z0358815GI2I8U5CTHXW

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Domain:
        DomainName: !Ref HostName
        CertificateArn: !Ref GenerateCertificate
        Route53:
          HostedZoneId: Z0358815GI2I8U5CTHXW
      StageName: !Ref Stage
      MethodSettings:
        - LoggingLevel: ERROR
          MetricsEnabled: True
          ResourcePath: "/*" # allows for logging on any resource
          HttpMethod: "*" # allows for logging on any method
      Auth: # Uses the FirebaseTokenAuthorizer to identify the session user. 
        ApiKeyRequired: false
        DefaultAuthorizer: FirebaseTokenAuthorizer
        Authorizers:
          FirebaseTokenAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: arn:aws:lambda:us-east-1:887279901853:function:FirebaseTokenAuthorizer
            Identity:
              ReauthorizeEvery: 300
              Headers: [ "Authorization" ]
      GatewayResponses: 
        UNAUTHORIZED: # This block allows customizing the message shown to user that are not logged in.
          StatusCode: 401
          ResponseTemplates:
            "application/json": '{ "message": "Please login." }'
        ACCESS_DENIED: # This block allows customizing the message shown to user denied.
          StatusCode: 403
          ResponseTemplates:
            "application/json": '{ "message": "Denied" }'
      Cors:
        AllowMethods: "'*'"
        AllowOrigin: "'*'"

  StripeCheckoutSession:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: checkout.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64 # if you are using Apple M1
      Timeout: 10
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
      Events:
        POST:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /checkout
            Method: post
            Auth: 
              Authorizer: NONE
        OPTIONS:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /checkout
            Method: options
            Auth: 
              Authorizer: NONE

  StripeConnectOnboard:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: onboard.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64 # if you are using Apple M1
      Timeout: 10
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
      Events:
        POST:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /onboard
            Method: post
        OPTIONS:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /onboard
            Method: options
            Auth: 
              Authorizer: NONE

  StripeConnectOnboardAcceptWebhook:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: onboard_accept.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64 # if you are using Apple M1
      Timeout: 10
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
      Events:
        POST:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /onboard/accept
            Method: post
            Auth: 
              Authorizer: NONE

  AcceptPaymentWebhook:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: accept.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64 # if you are using Apple M1
      Timeout: 10
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
      Events:
        POST:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /accept
            Method: post
            Auth: 
              Authorizer: NONE

  GetDashboardLoginLink:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: dashboard_login.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64 # if you are using Apple M1
      Timeout: 10
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
      Events:
        GET:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /dashboard-login
            Method: get

  Payout:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: payout.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64 # if you are using Apple M1
      Timeout: 10
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
      Events:
        POST:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /payout
            Method: post

Outputs:
  APIGateway:
    Description: API APIGateway endpoint URL for DEV stage for Hello World function
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/echo"
