name: "Setup"
runs:
  using: "composite"
  steps:
    - run: pip install poetry
      shell: bash
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        # cache: "poetry"
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: "npm"
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::209991057786:role/github-action-permissions-GithubActionRole"
    - name: Install
      run: |
        npm i -g prettier esbuild
        npm ci
        pip install isort
      shell: bash
