AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  gateway-service

  Sample SAM Template for gateway-service

Parameters:
  MainDomain:
    Type: String
  Route53ZoneId:
    Type: String
  Stage:
    Type: String
    Default: DEV
  Architecture:
    Type: String
    Default: arm64
  Authorizer:
    Type: String
    Default: UserAppTokenAuthorizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 2
    MemorySize: 3008
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  # Give account permission to log to CloudWatch. Probably only need once per
  # account.
  ApiCWLRoleArn:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  # IAM Role for API Gateway + CloudWatch Logging
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Action: "sts:AssumeRole"
          Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  GenerateCertificate: # Creates a valid certificate for the HTTP API endpoint under the custom domain
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join ["", ["*.", !Ref MainDomain]]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Join ["", ["*.", !Ref MainDomain]]
          HostedZoneId: !Ref Route53ZoneId

  GatewayAPI:
    Type: AWS::Serverless::Api
    Properties:
      Domain: # Configure the domain of the API
        DomainName: !Join ["", ["*.", !Ref MainDomain]]
        CertificateArn: !Ref GenerateCertificate
        Route53:
          HostedZoneId: !Ref Route53ZoneId
      StageName: !Ref Stage
      MethodSettings:
        - LoggingLevel: ERROR
          MetricsEnabled: True
          ResourcePath: "/*" # allows for logging on any resource
          HttpMethod: "*" # allows for logging on any method
      Auth: # Uses the UserAppTokenAuthorizer to identify the session user.
        ApiKeyRequired: false
        DefaultAuthorizer: !Ref Authorizer
        Authorizers:
          UserAppTokenAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !Sub arn:aws:lambda:us-east-1:${AWS::AccountId}:function:UserAppTokenAuthorizer
            Identity:
              ReauthorizeEvery: 300
              Headers: ["X-FAST-API-KEY"]

  CorsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cors
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - !Ref Architecture
      Events:
        CorsRoot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: NONE
            Path: /
            Method: OPTIONS
            RestApiId: !Ref GatewayAPI
        CorsAny:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: NONE
            Path: /{proxy+}
            Method: OPTIONS
            RestApiId: !Ref GatewayAPI

  GatewayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./gateway
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - !Ref Architecture
      Events:
        AnyRoot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: Any
            RestApiId: !Ref GatewayAPI
        Any:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: Any
            RestApiId: !Ref GatewayAPI
      Policies:
        - AmazonAPIGatewayInvokeFullAccess # This will allow this lambda to send http request to the graphql api
        - AWSLambdaRole # This will allow this lambda to send http request to the graphql api
        - AmazonSQSFullAccess # Allows sending billing to the graphql service
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TRUST_X_USER_EMAIL_HEADER: "" # Set to 1 to bypass authentication
          TRUST_X_USER_PK_HEADER: "" # Set to 1 to bypass authentication
          LOCAL_GRAPHQL: "" # Set to 1 to use http://host.docker.internal:4000 as the graphql server
          DEV_DOMAIN: "" # Set to 1 to use https://devfastchargeapi.com

Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GatewayAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${GatewayAPI}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
  GatewayFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GatewayFunction.Arn
  GatewayFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GatewayFunctionRole.Arn
