#!/bin/bash
if [ "$DEV_DOMAIN" == "1" ]; then
    secretArn=$(aws secretsmanager list-secrets --filter Key="name",Values="dev-search-service-AuroraDBSecret"  --query 'SecretList[0].ARN' --output text)
    dbArn="arn:aws:rds:us-east-1:209991057786:cluster:dev-search-service-auroradbcluster"
    aws rds-data execute-statement --resource-arn "$dbArn" --secret-arn "$secretArn" --sql "$1"
else
    secretArn=$(aws secretsmanager list-secrets --filter Key="name",Values="live-search-service-AuroraDBSecret"  --query 'SecretList[0].ARN' --output text)
    dbArn="arn:aws:rds:us-east-1:887279901853:cluster:live-search-service-auroradbcluster"
    aws --profile live_fastchargeapi rds-data execute-statement --resource-arn "$dbArn" --secret-arn "$secretArn" --sql "$1"
fi
