version = 0.1
[default.deploy.parameters]
stack_name = "dev-search-service"
s3_prefix = "dev-search-service"
region = "us-east-1"
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
parameter_overrides = "Stage=\"DEV\" MainDomain=\"devfastchargeapi.com\" Route53ZoneId=\"Z07362872NENGXHWMNLU5\" EnvDevDomain=\"1\""
resolve_s3 = true
image_repositories = []
no_fail_on_empty_changeset =  true

[default.logs.parameters]
stack_name = "dev-search-service"

[default.delete.parameters]
stack_name = "dev-search-service"
no_prompts = true

[live.deploy.parameters]
profile = "live_fastchargeapi"
stack_name = "live-search-service"
s3_prefix = "live-search-service"
region = "us-east-1"
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
parameter_overrides = "Stage=\"DEV\" MainDomain=\"fastchargeapi.com\" Route53ZoneId=\"Z0358815GI2I8U5CTHXW\""
resolve_s3 = true
image_repositories = []
no_fail_on_empty_changeset =  true

[live.logs.parameters]
profile = "live_fastchargeapi"
stack_name = "live-search-service"
