version = 0.1
[default.deploy.parameters]
stack_name = "search-service"
resolve_s3 = true
s3_prefix = "search-service"
region = "us-east-1"
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM"
parameter_overrides = "Stage=\"DEV\" GatewayHostNameV2=\"api.v2.search.fastchargeapi.com\""
image_repositories = []
