name: Deploy to AWS skipping tests
on:
  push:
    branches:
      - "deploy/no-test/all"

permissions:
  id-token: write
  contents: write

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: "--max_old_space_size=6144"

jobs:
  deploy-auth-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-push
        with:
          AWS_GITHUBACTIONROLE_ARN: ${{ secrets.AWS_GITHUBACTIONROLE_ARN }}
      - name: Build dependency
        run: |
          (cd graphql-service/apollo && npm ci && npm run prebuild)
          (cd auth-service && npm ci)
      - name: Deploy
        run: |
          cd auth-service
          npm run deploy

  deploy-graphql-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-push
        with:
          AWS_GITHUBACTIONROLE_ARN: ${{ secrets.AWS_GITHUBACTIONROLE_ARN }}
      - name: Build dependency
        run: |
          (cd graphql-service/apollo && npm ci && npm run prebuild)
      - name: Deploy
        run: |
          cd graphql-service
          npm run deploy

  deploy-gateway-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-push
        with:
          AWS_GITHUBACTIONROLE_ARN: ${{ secrets.AWS_GITHUBACTIONROLE_ARN }}
      - name: Build dependency
        run: |
          (cd graphql-service/apollo && npm ci && npm run prebuild)
          (cd gateway-service && npm ci)
      - name: Deploy
        run: |
          cd gateway-service
          npm run deploy

  deploy-payment-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-push
        with:
          AWS_GITHUBACTIONROLE_ARN: ${{ secrets.AWS_GITHUBACTIONROLE_ARN }}
      - name: Build dependency
        run: |
          (cd graphql-service/apollo && npm ci && npm run prebuild)
          (cd payment-service && npm ci)
      - name: Deploy
        run: |
          cd payment-service
          npm run deploy
